server:
  port: 9091
  host: localhost
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/wn_parking?useSSL=false&charaterEncode=utf-8&serverTimezone=GMT%2B8
      username: root
      password: root
      initial-size: 5 #初始化连接数
      max-active: 50 #最大连接数
      max-wait: 6000 #获得连接的超时时间
      min-idle: 5 #最小空闲数
      time-between-eviction-runs-millis: 60000 #间隔1分钟检查一次空闲连接
      min-evictable-idle-time-millis: 300000 #超过空闲5分钟以上的连接，都会被物理关闭
      pool-prepared-statements: true #运行缓存预编译对象
      max-pool-prepared-statement-per-connection-size: 50 #允许缓存50个连接
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=1000;
      filters: stat,wall,slf4j
      web-stat-filter:
        enabled: true #开启德鲁伊的web监控
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,*.html
      stat-view-servlet:
        enabled: true #德鲁伊的web监控界面
        url-pattern: /druid/* #http://localhost:8080/druid/
        reset-enable: false #不需要重置SQL数据
        login-username: admin
        login-password: 123456
        allow: #设置白名单
        deny: #设置黑名单
      aop-patterns: com.woniuxy.user.* #监控url请求路径
  redis:
    host: 192.168.200.130
    port: 6379
    database: 0
    password: philredis
  rabbitmq:
    host: 192.168.200.130
    port: 5672
    username: admin
    password: philrabbitmq
    virtual-host: parkingsys
    publisherConfirmType: correlated #确认消息是否已发送至交换机
    publisherReturns: true #确认消息是否已发送至队列
    listener:
      direct:
        acknowledge-mode: manual #通过交换机过来的信息开启手动确认
      simple:
        acknowledge-mode: manual #不通过交换机过来的信息也开启手动确认

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  elasticsearch:
    uris: http://${server.host}:9200 #配置ES的连接地址
jwt:
  signature: woniu
  accessTime: 60 #短令牌有效期 单位：分钟
  refreshTime: 7 #长令牌有效期 单位：天
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #尊重驼峰命名规则
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.woniuxy.user.entity


