server:
  port: 9090
  host: 192.168.1.50
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/wn_parking?charaterEncode=utf8&serverTimezone=GMT%2B8
      username: root
      password: root
      initial-size: 5 #初始化连接数
      max-active: 50 #最大连接数
      max-wait: 6000 #获得连接的超时时间
      min-idle: 5 #最小空闲数
      time-between-eviction-runs-millis: 60000 #间隔1分钟检查一次空闲连接
      min-evictable-idle-time-millis: 300000 #超过空闲5分钟以上的连接，都会被物理关闭
      pool-prepared-statements: true #运行缓存预编译对象
      max-pool-prepared-statement-per-connection-size: 50 #允许缓存50个连接
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=1000;
      filters: stat,wall,slf4j
      web-stat-filter:
        enabled: true #开启德鲁伊的web监控
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,*.html
  redis:
    host: ${server.host}
    port: 6379
    database: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd
  elasticsearch:
    uris: http://${server.host}:9200
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #不尊重驼峰命名规则
  type-aliases-package: com.woniuxy.operator.entity ,com.woniuxy.operator.vo
jwt:
  signature: Ken
  accessTime: 5 #短令牌有效时间,单位:分钟
  refreshTime: 7 #长令牌有效时间,单位:天